export const cartTypes = {
    CART_ADD_ITEM: 'CART_ADD_ITEM',
    REMOVE_CART_ITEM: 'REMOVE_CART_ITEM',
    CART_SAVE_SHIPPING_ADDRESS: 'CART_SAVE_SHIPPING_ADDRESS',
    CART_SVAE_PAYMENT_METHOD: 'CART_SVAE_PAYMENT_METHOD',
    CART_ADD_ITEM_FAIL: 'CART_ADD_ITEM_FAIL',
    CART_EMPTY: 'CART_EMPTY',
}