export const orderTypes = {
    ORDER_CREATE_REQUEST: 'ORDER_CREATE_REQUEST',
    ORDER_CREATE_SUCCESS: 'ORDER_CREATE_SUCCESS',
    ORDER_CREATE_FAIL: 'ORDER_CREATE_FAIL',
    ORDER_CREATE_RESET: 'ORDER_CREATE_RESET',

    ORDER_DETAILS_REQUEST: 'ORDER_DETAILS_REQUEST',
    ORDER_DETAILS_SECCESS: 'ORDER_DETAILS_SECCESS',
    ORDER_DETAILS_FAIL: 'ORDER_DETAILS_FAIL',

    ORDER_PAY_REQUEST: 'ORDER_PAY_REQUEST',
    ORDER_PAY_SUCCESS: 'ORDER_PAY_SUCCESS',
    ORDER_PAY_FAIL: 'ORDER_PAY_FAIL',
    ORDER_PAY_RESET: 'ORDER_PAY_RESET',

    ORDER_MINE_LIST_REQUEST: 'ORDER_MINE_LIST_REQUEST',
    ORDER_MINE_LIST_SUCCESS: 'ORDER_MINE_LIST_SUCCESS',
    ORDER_MINE_LIST_FAIL: 'ORDER_MINE_LIST_FAIL',
}