const data = {
    products: [
        {
            _id: '1',
            name: 'Nike slim shirt',
            category: 'Shirt',
            image: '/images/p1.jpg',
            price: 120, 
            countInstock: 10,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'High quality product',
        },
        {
            _id: '2',
            name: 'Adidas slim shirt',
            category: 'Shirt',
            image: '/images/p2.jpg',
            price: 160, 
            countInstock: 20,
            brand: 'Adidas',
            rating: 4.5,
            numReviews: 10,
            description: 'High quality product',
        },
        {
            _id: '3',
            name: 'Lakosa slim trouser',
            category: 'Trouser',
            image: '/images/p3.jpg',
            price: 250, 
            countInstock: 0,
            brand: 'Lakosa',
            rating: 4.5,
            numReviews: 20,
            description: 'High quality product',
        },
        {
            _id: '4',
            name: 'Gusi slim shirt',
            category: 'Shirt',
            image: '/images/p4.jpg',
            price: 180, 
            countInstock: 15,
            brand: 'Gusi',
            rating: 4.5,
            numReviews: 12,
            description: 'High quality product',
        },
        {
            _id: '5',
            name: 'Puma slim pant',
            category: 'Pant',
            image: '/images/p5.jpg',
            price: 80, 
            countInstock: 5,
            brand: 'Puma',
            rating: 4.5,
            numReviews: 17,
            description: 'High quality product',
        },
        {
            _id: '6',
            name: 'Timber land slim pant',
            category: 'Pant',
            image: '/images/p6.jpg',
            price: 65, 
            countInstock: 12,
            brand: 'Timber land',
            rating: 4.5,
            numReviews: 15,
            description: 'High quality product',
        },
    ],
};
export default data;